### ISSUE TITLE
Introduce official supporters

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#119]
As a site admin, I want to be able to add partners of type _official supporters_. They should appear between the bronze sponsors and the community and media partners.

**Comment by gochev** [comment]
They are called Partners.

Partners right now have 2 types.
Media and Other... 
MEDIA are clear.
OTHERS is something to be used as Baristo and etc..

I will add a new type called OFFICIAL_SUPPORTERS

also we do not have Bronze partenrs..

we have PLATINUM, GOLD and SILVER.
