### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#12]
- The font on the site is very small
- The jPrime logo is too small
- There is no favicon at the moment

**Comment by gochev** [comment]
should be done

**Comment by gochev** [comment]
ah ok favicon only on homepage still

**Comment by ivannov** [comment]
Hmm, Mitia told us that it is fixed, however you should clean up the browser caches

**Comment by gochev** [comment]
it is done
the problem was it was starting with / ishntead of just without the / so on some LONG urls like /article/1 and etc it was not working
