### ISSUE TITLE
If a speaker is featured but not marked as accepted detailed speaker profile is not displaying

### ISSUE THREAD

**Issue by martinfmi** [bgjug/jprime#177]
Steps to reproduce:

- go to speakers;
- create a new featured speaker (don't mark accepted);
- navigate to https://jprime.io/speaker/speaker_id

Screen is broken (no image and description are displayed).

**Comment by gochev** [comment]
even featured speakers has to be accepted. The reason is that "accepted" means "SHOW ON THE WEBSITE" ... featured... I dont know what means :D nothing :D so ... ignore the "featured" just use accepted for everything.

**Comment by gochev** [comment]
Closing this since not a defect ;) it works by design :)
