### ISSUE TITLE
Send more than one proposal

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#19]
At the moment there is no way for a speaker to send more than one proposal. The reason is that there is constraint in the DB for unique emails. And the current functionality always adds the speaker info as a new speaker to the DB

Maybe a good idea is to check whether speaker with that email exists. And if they exist, set it to the submission and only persist the submission.

It is good idea to state in the CFP page above the speaker data fields something along these lines:

If you have already submitted a proposal, just enter the email that you used and this submission will be automatically assigned to you.

**Comment by gochev** [comment]
nah we want to be sure that we have ALL info .. so we will keep him asking for everythign however we will not create a new speaker if we already have one ...
