### ISSUE TITLE
Create invoice PDF and send an email

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#23]
Once the ticket payment process is finished, an invoice PDF should be generated (see InvoiceExporter.main). There's a TODO already in the TicketsController.createPDFAndSendToEmail() method.
After the invoice is created, this PDF should be sent to the registrant email address from tickets@jprime.io containing the PDF and a sample text that the registration finished successfully.

An example of sending emails can be found in one of the CfpControllers. Please follow the same pattern for the sake of consistency.

**Comment by martinfmi** [comment]
TicketsController.createPDFAndSendToEmail() това ще се разбие за да е
по-highly cohesive

2015-04-20 14:32 GMT+03:00 Ivan St. Ivanov <notifications@github.com>:
