### ISSUE TITLE
Show the list of all registered visitors

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#27]
The admin panel should have a screen, which lists all the registered visitors: their names, their email addresses and the status (whether they 'payed', they 'requested' the payment or they are part of a 'sponsored' group coming from one of the sponsoring companies)

The actions that we need for each entry is edit, remove and set to paid (which should only appear if the status is 'requested').

**Comment by dalexandrov** [comment]
@ivannov since the changes are quite radical, I've created a branch "visitors". Please confirm the functionality is as expected. currently it fully corresponds to the requests above. 
Please see the comments in code.

**Comment by ivannov** [comment]
- Both commits should be squashed in one
- Visitor's status is better to be enum, not just string (check the SessionLevel in Submission)
- Why did you change the cascade type of Registrant in Visitor.java to CascadeType.ALL? I think that this is not correct - if you remove a visitor, you will remove the registrant (his company) as well
- The only available operation for most of my test visitor was remove. Edit should always be available, not only if the status is 'requesting'. The requirement "should only appear if the status is 'requested'" applies for the third action, which you did not implement
- When you click remove, it goes to admin/visitor/view.jsp. It should rather redirect to admin/visitor/view (like the add method)
- In Visitor controller, the name of the GET method is submissionForm. It doesn't make sense.
- The GET method in Visitor controller should support pagination

**Comment by dalexandrov** [comment]
* fixed sorting;
* fixed status;
* fixed edit;
* fixed relations;
* squashed commit;
* pagination will be moved to a separate task, lots of work;
* edit status is set free select, in case if admin sets it wrong.

:)

**Comment by dalexandrov** [comment]
@ivannov I've Completed rebase, fixed issues. Regarding removal of Registrant in Visitors list I kept both  conditions. If everything is ok i'll squash and rebase to master.

**Comment by ivannov** [comment]
Looks OK. Please squash, rebase to master and push
