### ISSUE TITLE
The registration form should contain company name field

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#28]
When the official registration form is displayed, the information available for a registrant is name and email. However, when we create the badges, we also want to fill in the company information there. That is why a third field should be added for each visitor: Company.

When Add new button is pressed on the registration form, the content of the Company of the first visitor should be copied.

**Comment by martinfmi** [comment]
PR created: https://github.com/bgjug/jprime/pull/30

**Comment by martinfmi** [comment]
A new 'company' field is added along with the name and email of the registrant - it is automatically copied from the previous visitor when a new one is added (typically bulk addition of registrants implies they are from the same company but there might be a case when they are from different companies and the same invoice for all of them may be generated).
