### ISSUE TITLE
Articles should be returned in reverse order

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#31]
At the moment when I click on Blog the list is returned so that the first article is on the top. However, the order should be reversed - the newest one should be first.

**Comment by gochev** [comment]
done .. :) keep in mind there is a valid URL just /nav which shows ALL articles ... maybe we should hide this.. :) (remove this controller handler ) I dont think it is used... and dont know why it is there...
anyway the order of it is also fixed... you can see the RIGHT Spring Data JPA way .. and the ... well other way :)
