### ISSUE TITLE
Sponsors must be moved below coorganizers

### ISSUE THREAD

**Issue by martinfmi** [bgjug/jprime#33]
Sponsors must be moved below coorganizers and styled in the same way on a second row - no need to have companies all over the site.

**Comment by gochev** [comment]
in the contract we believe we said that the sponsor logos will be at the bottom the co organizers at the top.

also I dont think that they should be on the top.. so lets keep them at the bottom .. I hope some other sponsor will join :+) and we will not have just 1.. but if they stay like that we can make them in a single ROW ( at the bottom ) with a type in brackets bellow or something like that 

I think now is good enougth .. hopefully some other sponsor will shown :+)

**Comment by ivannov** [comment]
No comments neither here, nor in the mailing list. I guess Marto is fine with that? If not, reopen (with some reasoning hopefully) :)
