### ISSUE TITLE
payment: A more meaningful results page

### ISSUE THREAD

**Issue by mihailstoynov** [bgjug/jprime#35]
now after payment the user sees this text:

> Thank you for buying tickets for JPrime conference
> The results page looks kind of empty. It can be made better with more info and better text.

Also, the results page has only two options "result("ok", model);" and not okay, which might be made better by having 4 options: payment by bank, cc, epay, or ERROR. and more meaningful messages.

**Comment by ivannov** [comment]
Is the current text fine? I think it is OK, but I don't know what you mean by meaningful message
