### ISSUE TITLE
NavController 

### ISSUE THREAD

**Issue by gochev** [bgjug/jprime#4]
NavController should get the articles in one tag (passed by param) and set this in the model + redirect to a jsp page
that looks like blog.html 

NavController should have one more method to display a single article (based on name(id)) blog-left-sidebar or right-sidebar.html

**Comment by dalexandrov** [comment]
I've pushed my changes! Hope it didn't screw it all. Ivannov, please take over for tags.

**Comment by dalexandrov** [comment]
Fixed articles, tags + footer style issues.
