### ISSUE TITLE
payment: Invoice to whom if two or more tickets and no company invoice requested

### ISSUE THREAD

**Issue by mihailstoynov** [bgjug/jprime#40]
If two tickets are requested and the guys don't care about invoice, whose name should be on the invoice? The first guy? For me it doesn't matter. But user must know tha the invoice will be issued to the first guy.

**Comment by dalexandrov** [comment]
Two separate invoices.

**Comment by ivannov** [comment]
I suppose that if the attendees don't care about the invoice, then it should be the easiest way for our accountants

**Comment by ivannov** [comment]
It's not an issue yet, but rather a matter of discussion. At the moment the invoice is issued to the first visitor (if it is not a company). Please reopen this or new issue if you (or better: our accountant) think that this should be changed
