### ISSUE TITLE
Font styles in agenda

### ISSUE THREAD

**Issue by martinfmi** [bgjug/jprime#46]
Font styles in agenda must be fixed since currently it is a little bit obscure and hard to read:
http://jprime.io/nav/Agenda

**Comment by gochev** [comment]
I dont see anything weird with the fonts can you explain pls

**Comment by ivannov** [comment]
From the feedback that I got, the issue was that they are yellow and quite hard to distinguish from the white background.

I know they are part of the theme, but this does not make them more readable ;)

**Comment by gochev** [comment]
every link in the theme is orange/yellow ... mmm we can make them bolder ? to be more easily visible .. or propose a color...

**Comment by ivannov** [comment]
Can you try with several colors and see which one fits best? But please don't change the theme, make the change just for this page

**Comment by gochev** [comment]
I made it just bolder for now ... it is an ARTICLE .. so everyone can just go in admin and change the article .. and the styles... however the way how Mitia made the PREVIEW ones published .. you cannot preview ytour changes.. you have to APPLY them .. (save) which is bad,... and I don't want to experiment with colors ..

**Comment by ivannov** [comment]
I think it is better know. Even better: no change in the theme. I will close this. @martinfmi if you have any objections, please reopen the issues and state them

**Comment by dalexandrov** [comment]
@gochev The task was to make a preview of the unpublished articles. So it works as expected.
