### ISSUE TITLE
Registrants in the panel

### ISSUE THREAD

**Issue by mihailstoynov** [bgjug/jprime#49]
1. The visitors tab should be renamed to REGISTRANTS
2. it should look like this:

Registrant, all data of the registrant (edit) [edit allows to edit all the visitors too and add remove them]
->visitor1 
->visitor2...
Registrant2, all data of the registrant (edit) [edit allows to edit all the visitors too and add remove them]

Example:
SAP labs, EIK, VAT number, ...all the data (edit button)
->ivan ivanov (ivan@sap)....
->petya slavova (petya@sap)....

**Comment by gochev** [comment]
I believe you should not rename visitors to registrants...


I believe an ew entity registrant should be created which contains multiple visitors...

the visitors to stay as it is .. the registrant to be like a parent to them

**Comment by ivannov** [comment]
That's how I am doing it. You can monitor my current progress here:
https://github.com/ivannov/jprime/commit/58dbdb740958e57b06cf39251f8d8798ecb9ec26

**Comment by ivannov** [comment]
Done. See https://github.com/bgjug/jprime/commit/09b9a77101a7901bcd4203dc3d07ab3ef6600552
