### ISSUE TITLE
translation of the invoices in bulgarian

### ISSUE THREAD

**Issue by mihailstoynov** [bgjug/jprime#51]
Please translate the invoices in bulgarian, so the user has an option of what kind of invoice to receive

**Comment by dalexandrov** [comment]
Invoices translated. Please, give more details on where the user should change the language.

**Comment by ivannov** [comment]
At the moment there is no need for that. We will only issue in Bulgarian. If we need to support english as well, we'll add a new issue

**Comment by dalexandrov** [comment]
Ok, I'll then switch the templates
