### ISSUE TITLE
MAJOR ISSUE: "invoice" button missing on registrant with first 8xxxxxx invoice number

### ISSUE THREAD

**Issue by mihailstoynov** [bgjug/jprime#58]

**Comment by dalexandrov** [comment]
Give example. Currently only Registrants with type EPAY_ACCOUNT are missing the invoice button, which is OK

**Comment by ivannov** [comment]
Unfortunately I can't link the requirement, but as @dalexandrov mentioned, all these registrants came from EPAY. And you requested that there is no link for such registrants. I am closing this issue

**Comment by mihailstoynov** [comment]
The button should be available on all registrants. Even on epay. Our current case requires it
