### ISSUE TITLE
Export the visitors from the database

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#65]
As conference admin I want to be able to export the list of all the visitors, so that I can use them for activities like printing the badges

The visitors should be exported in csv (comma separated value) format, so that they can be opened in a spreadsheet like MS Excel. The information for each visitor should contain their name, their company and their payment status. The latter will only be used by us, will not be sent to the badge print company,

**Comment by gochev** [comment]
I will add email as well to this list...

HOWEVER keep in mind .. that dont know who made the Visitor but ALL of the fields are OPTIONAL .. which means it is possible to have no company no name and no email :)
