### ISSUE TITLE
Images resizer... https://code.google.com/p/thumbnailator/

### ISSUE THREAD

**Issue by gochev** [bgjug/jprime#7]
Images resizer... https://code.google.com/p/thumbnailator/

Maybe some javascript library for .. editing the image visually

**Comment by martinfmi** [comment]
For which images ? sponsors ? please clarify

**Comment by dalexandrov** [comment]
Ivaylo has made a pull request with that, please check.

**Comment by ivannov** [comment]
PR closed

**Comment by gochev** [comment]
its better to use https://github.com/rkalla/imgscalr
