### ISSUE TITLE
Paging in admin

### ISSUE THREAD

**Issue by gochev** [bgjug/jprime#73]
In the admin interface we should have "paging" for list views.

Currently they display only 20 items... EVERYTHING supports spring data pating so you can pass ?size for size of a page  param for page number.

Only the JSP logic has to be made so the end result  should look something like :

<img width="322" alt="screen shot 2016-02-29 at 16 39 33" src="https://cloud.githubusercontent.com/assets/5537142/13397529/08895dd8-df03-11e5-884b-ad2638f5a020.png">

**Comment by gochev** [comment]
Adding paging where possible.

However the articles and registrants where not developed based on the guidelines for other views so the paging is not added there yet.

https://github.com/bgjug/jprime/commit/f67441a9e861c59783d6510a9d01cb2a0d89367d

**Comment by dalexandrov** [comment]
wilco

**Comment by ivannov** [comment]
We will change our site design, so closing this
