### ISSUE TITLE
Adding CFP submission from the admin panel references wrong speaker

### ISSUE THREAD

**Issue by martinfmi** [bgjug/jprime#78]
Use case:

1) submission created from admin panel with speaker A
2) second submission created fro admin panel with speaker B
3) the second submissions displays with speaker A which is wrong - there is an issue with how the Submission and User tables are joined.

**Comment by martinfmi** [comment]
Actually the issue occurs because the email address of the second user is the same as this of the first one and the application tries to find an already existing speaker with the same mail which is a little bit misleading.

**Comment by ivannov** [comment]
This will be fixed once we have user management for CFP (#120)
