### ISSUE TITLE
when GET http://jprime.io/nav/2017 then NoSuchElementException

### ISSUE THREAD

**Issue by hexmind** [bgjug/jprime#84]
when GET http://jprime.io/nav/2017 
then java.util.NoSuchElementException
expected 404 page
and no stack trace :)

> java.util.NoSuchElementException
	java.util.ArrayList$Itr.next(ArrayList.java:854)
	java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	site.controller.NavController.getByTag(NavController.java:40)

**Comment by gochev** [comment]
I am aware we are not sending the right http code ;) but we generally never return 404 :) 

We are developers (a bit lazy) and this is a site for developers :) so we intentionally don't handle 404 or 500 or anything so every developer can see the error :) and sometimes.. even workaround it. Of course you are welcome to send pull request it is a 1min fix.

Offtopic: 
I still remember when we had registrations and someone tried to register when he was already registered so duplicated email was happening and his (actually her) next message was "ahh so I already have registrationnn hmm :) let me find the pass" anyway it was fun... so yes.. we do not handle any exceptions so no 404 no specific 500 or anything.
