### ISSUE TITLE
Prevent bots to register or submit sessions

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#85]
It is now possible for bots to submit a new session with POST to `/cfp` or to register as attendees with POST to `/tickets/epay`.

The site should have a capcha-like functionality that disallows that.

So far we've seen just bots register as attendees, so it should be disabled for the moment for CFP. And be easily to enable there as well.

**Comment by gochev** [comment]
Captcha has been added but the tests are NOT UPDATED so if new deployment is required skip tests.
