### ISSUE TITLE
Show latest submissions

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#86]
As an administrator
I want to see only the current conference submissions when I go to http://jprime.io/admin/submission/view
So that it's easier to find what I need to vote

Optionally, there may be a button or link on the top of the page that toggles between all submissions and current conference submissions

**Comment by imarudina** [comment]
Please check pull request: https://github.com/bgjug/jprime/pull/88

**Comment by gochev** [comment]
so this should be fixed
