### ISSUE TITLE
payment provider (epay.bg)

### ISSUE THREAD

**Issue by gochev** [bgjug/jprime#9]

**Comment by gochev** [comment]
Integration .. but HIGH LEVEL ABSTRACTION havent researched how the epay integration actually works.

Kinda like CFP

Dedicated Controller + Page(jsp) with a form

the form should have:
First Name, LastName, Company Name, Position (we may use User entity with additional field and aditional boolean "isPaid" and maybe some transaction id ? ) 

ones HIT REGISTER ... 

we redirect/reopen to the SAME page after submit (maybe passing the ID of the customer as param to know he is registered but payment is waiting) .. but this time showing a BUTTON Pay with ePay.bg (where we pass the data of the merchant and the 80$ price) ones the user PAYS in ePay.bg he will get REDIRECTED to the same PAGE he was at.. this time epay will provide parameter for the status of the order and I guess some ID to know that this redirect is coming from epay.bg (not sure how epay handles this) however ones this is confirmed we change the boolean of the user to isPaid = true.

IF ePay.bg have a backend api call to check the status of an order we have to use spring scheduler ( http://docs.spring.io/spring/docs/current/spring-framework-reference/html/scheduling.html ) then lets say every 10-15-30mins checks in a LIST of unpaid transaction IDs is some of them paid or not.

**Comment by ivannov** [comment]
Closing this one after opening https://github.com/bgjug/jprime/issues/22
