### ISSUE TITLE
Support for two types of sessions

### ISSUE THREAD

**Issue by ivannov** [bgjug/jprime#94]
At the moment jPrime supports just one type of talks - the conference sessions. But we want to introduce a second one - workshops.

**As a speaker**, I want to be able to specify which type of session I submit - Conference session (50 minutes) or Workshop (3 hours).

**As a conference organizer**, when I look at the list of submissions, I want to also see the type of each submission.

**Comment by kotse** [comment]
Should the default be Conference session?

**Comment by ivannov** [comment]
Yes, Conference session should be the default option on the submission dialog
